dataset:
  name: "rotation"
  train_path: 
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/train_0.hdf5"
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/train_1.hdf5"
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/train_2.hdf5"
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/train_3.hdf5"
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/train_4.hdf5"
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/train_5.hdf5"
  test_path:
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/test_0.hdf5"
    - "/home/dp332/dp332/dc-su2/dc-su2/rotation3/test_1.hdf5"
  grid: 64
  batch_size: 128
  statistics: 
    path: "data/preprocess/statistic/rotation3.hdf5"
    values:
      - name: velocity
        stats: ['mean','std']
      - name: temperature
        stats: ['min','median']
      - name: density
        stats: ['min','median']
      - name: intensity
        stats: ['min','median']

model:
  seed: 1234
  epochs: 500
  alpha: 0.8
  beta: 0.2

optimizer:
  type: "adam"
  params:
    lr: 0.0004
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false

# scheduler:
#   type: "step"
#   params:
#     step_size: 200
#     gamma: 0.1

output:
  save_path: "../results/rotation"
  log_file: "log_file.txt"
  model_file: "model.pth"
  pkl_file: "history.pkl"
  history_img: 'history.png'
  img_dir: "../results/rotation/img"
