dataset:
  name: "faceon"
  path: "/home/dc-su2/rds/rds-dirac-dr004/Magritte/clean_random_grid64_data0.hdf5"
  grid: 64
  batch_size: 128
  df: 0.1
  statistics: 
    path: "/home/dc-su2/physical_informed/cnn/statistic/random.hdf5"
    values:
      - name: intensity
        min : 'y/min'
        median: 'y/median'

model:
  seed: 1234
  epochs: 500
  alpha: 0.8
  beta: 0.2

optimizer:
  type: "adam"
  params:
    lr: 0.0004
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false

# scheduler:
#   type: "step"
#   params:
#     step_size: 200
#     gamma: 0.1

output:
  save_path: "/home/dc-su2/rds/rds-dirac-dp225-5J9PXvIKVV8/3DResNet/grid64/rotate/results/sql"
  logfile: "log_file.txt"
  model_name: "model.pth"
  results: "history.pkl"