dataset:
  name: "faceon"
  grid: 64
  batch_size: 128
  statistics: 
    path: "dataset/preprocess/statistic/faceon.hdf5"
    values:
      - name: velocity
        stats: ['mean','std']
      - name: temperature
        stats: ['min','median']
      - name: density
        stats: ['min','median']
      - name: intensity
        stats: ['min','median']

model:
  seed: 1234
  epochs: 500
  alpha: 0.8
  beta: 0.2
  resume_checkpoint: "/home/dp332/dp332/dc-su2/results/pretrained.pth"
  # resume_checkpoint: null

optimizer:
  type: "adam"
  params:
    lr: 0.0004
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0
    amsgrad: false

# scheduler:
#   type: "cyclic"
#   params:
#     base_lr: 0.0004
#     max_lr: 0.04
#     step_size_up: 100
#     step_size_down: null  # If null, step_size_down is set to step_size_up
#     mode: "triangular"
#     gamma: 1.0
#     cycle_momentum: false 

output:
  save_path: "../results/faceon"
  log_file: "log_file.txt"
  model_file: "model.pth"
  pkl_file: "history.pkl"
  history_img: 'history.png'
  img_dir: "../results/faceon/img"