dataset:
  name: "mulfreq"
  grid: 64
  batch_size: 512
  statistics: 
    path: "dataset/preprocess/statistic/mulfreq.hdf5"
    values:
      - name: velocity
        stats: ['mean','std']
      - name: temperature
        stats: ['min','median']
      - name: density
        stats: ['min','median']
      - name: intensity
        stats: ['min','max']

model:
  stage: 2
  seed: 1234
  epochs: 500
  alpha: 0.8
  # pretrained_encoder: "/home/dp332/dp332/dc-su2/results/pretrained.pth"
  resume_checkpoint: "/home/dp332/dp332/dc-su2/results/mulfreq/ro_200_2/ro_200_2.pth"

optimizer:
  type: "adam"
  params:
    lr: 0.0004
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false

output:
  save_path: "results/mulfreq"
  log_file: "log_file.txt"
  model_file: "model.pth"
  pkl_file: "history.pkl"
  history_img: 'history.png'
  img_dir: "results/mulfreq/img"