dataset:
  name: "rotation"
  grid: 64
  batch_size: 512
  statistics: 
    path: "dataset/preprocess/statistic/rotation.hdf5"
    values:
      - name: velocity
        stats: ['mean','std']
      - name: temperature
        stats: ['min','median']
      - name: density
        stats: ['min','median']
      - name: intensity
        stats: ['min','median']
        # min : 'y/min'
        # median: 'y/median'

model:
  seed: 1234
  epochs: 500
  alpha: 0.8
  beta: 0.2
  resume_checkpoint: "/home/dp332/dp332/dc-su2/results/rotation/batch_512_001_2/batch_512_001_2.pth"
  # resume_checkpoint: null

optimizer:
  type: "adam"
  params:
    lr: 0.0004
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false

use_scheduler: true
scheduler:
  - type: "StepLR"
    params:
      step_size: 40
      gamma: 0.1
  - type: "CosineAnnealingLR"
    params:
      T_max: 50
      eta_min: 0.001
      
ddp_on: False
output:
  save_path: "../results/rotation"
  log_file: "log_file.txt"
  model_file: "model.pth"
  pkl_file: "history.pkl"
  history_img: 'history.png'
  img_dir: "../results/rotation/img"
